--1)
SELECT F.NOME, F.CPF, COUNT(C.FESTA), SUM(C.PRECO)
	FROM CLIENTE_FISICO F JOIN CONTRATO C 
	ON F.CODIGO=C.CLIENTE
	WHERE EXTRACT(YEAR FROM C.DATA) >= EXTRACT(YEAR FROM SYSDATE) - 5
	GROUP BY F.CPF, F.NOME
	ORDER BY SUM(C.PRECO) DESC;

--2) tested
SELECT NATUREZA, COUNT(NATUREZA)
	FROM CLIENTE
	GROUP BY NATUREZA;
	/* Calcular a razão em aplicação */


--3) tested
SELECT CARGO, AVG(SALARIO) AS SALARIO_MEDIO, COUNT(CPF) AS NUM_EMPREGADOS
	FROM FUNCIONARIO
	GROUP BY CARGO
	ORDER BY AVG(SALARIO);

--4) not complete
SELECT 
	ADICIONAR DATA NA ENTIDADE CONTRATO.

--5) not complete
SELECT FU.NOME, FU.CPF, COUNT(S.FESTA), SUM(FE.DURACAO)
	FROM SUPERVISOR JOIN FUNCIONARIO FU
	ON SUPERVISOR.CPF=FU.CPF
	JOIN SUPERVISIONA S
	ON FU.CPF=S.SUPERVISOR
	JOIN FESTA F
	ON F.CODIGO=S.FESTA
	WHERE 