--1)
SELECT F.NOME, F.CPF, COUNT(C.FESTA) AS NUM_FESTAS, SUM(C.PRECO) AS TOTAL_FESTAS
	FROM CLIENTE_FISICO F JOIN CONTRATO C 
	ON F.CODIGO=C.CLIENTE
	WHERE EXTRACT(YEAR FROM C.DATA) >= EXTRACT(YEAR FROM SYSDATE) - 5
	GROUP BY F.CPF, F.NOME
	ORDER BY SUM(C.PRECO) DESC;

--2)
SELECT NATUREZA, COUNT(NATUREZA)
	FROM CLIENTE
	GROUP BY NATUREZA;
	/* Calcular a razão em aplicação */


--3)
SELECT CARGO, AVG(SALARIO) AS SALARIO_MEDIO, COUNT(CPF) AS NUM_EMPREGADOS
	FROM FUNCIONARIO
	GROUP BY CARGO
	ORDER BY AVG(SALARIO) DESC;

--4) not tested
SELECT F.NOME, F.CPF, COUNT(C.FESTA) AS NUM_FESTAS, SUM(C.PRECO) AS TOTAL_VENDIDO
	FROM VENDEDOR V JOIN FUNCIONARIO F
	ON V.CPF=F.CPF
	LEFT JOIN CONTRATO C
	ON C.VENDEDOR=F.CPF
	WHERE C.DATA >= SYSDATE - 30
	GROUP BY F.CPF, F.NOME
	ORDER BY SUM(C.PRECO) DESC;

--5)
SELECT FU.NOME, FU.CPF, COUNT(S.FESTA) AS NUM_FESTAS, SUM(FE.DURACAO) AS TEMPO_TOTAL
	FROM SUPERVISOR JOIN FUNCIONARIO FU
	ON SUPERVISOR.CPF=FU.CPF
	JOIN SUPERVISIONA S
	ON FU.CPF=S.SUPERVISOR
	JOIN FESTA FE
	ON FE.CODIGO=S.FESTA
	WHERE FE.DATA_HORA >= SYSDATE - 30 AND FE.DATA_HORA < SYSDATE
	GROUP BY FU.CPF, FU.NOME
	ORDER BY SUM(FE.DURACAO) DESC;

--6) not tested
SELECT SUM(F.SALARIO) AS GASTO_SALARIOS, SUM(C.PRECO) AS ARRECADACAO_FESTAS
	FROM FUNCIONARIO F, CONTRATO C
	WHERE (C.DATA >= SYSDATE - 30) AND (C.DATA < SYSDATE);

--7) not tested
SELECT L.NOME, COUNT(F.CODIGO) AS NUM_FESTAS, SUM(C.PRECO) AS PRECO_TOTAL, L.CEP, L.NUMERO
	FROM LOCAL L JOIN FESTA F
	ON (L.CEP=F.CEP) AND (L.NUMERO=F.NUMERO)
	JOIN CONTRATO C
	ON C.FESTA=F.CODIGO
	WHERE F.DATA_HORA >= SYSDATE - 30 AND F.DATA_HORA < SYSDATE
	GROUP BY L.CEP, L.NUMERO, L.NOME
	ORDER BY SUM(C.PRECO) DESC;
