--1)
SELECT F.NOME, F.CPF, COUNT(C.FESTA) AS NUM_FESTAS, SUM(C.PRECO) AS TOTAL_FESTAS
	FROM CLIENTE_FISICO F JOIN CONTRATO C 
	ON F.CODIGO=C.CLIENTE
	WHERE EXTRACT(YEAR FROM C.DATA) >= EXTRACT(YEAR FROM SYSDATE) - 5
	GROUP BY F.CPF, F.NOME
	ORDER BY SUM(C.PRECO) DESC;

--2)
SELECT NATUREZA, COUNT(NATUREZA)
	FROM CLIENTE
	GROUP BY NATUREZA;
	/* Calcular a razão em aplicação */


--3)
SELECT CARGO, AVG(SALARIO) AS SALARIO_MEDIO, COUNT(CPF) AS NUM_EMPREGADOS
	FROM FUNCIONARIO
	GROUP BY CARGO
	ORDER BY AVG(SALARIO) DESC;

--4) not tested
SELECT F.NOME, F.CPF, COUNT(C.FESTA) AS NUM_FESTAS, SUM(C.PRECO) AS TOTAL_VENDIDO
	FROM VENDEDOR V JOIN FUNCIONARIO F
	ON V.CPF=F.CPF
	LEFT JOIN CONTRATO C
	ON C.VENDEDOR=F.CPF
	WHERE C.DATA >= SYSDATE - 30
	GROUP BY F.CPF, F.NOME
	ORDER BY SUM(C.PRECO) DESC;

--5) not complete
SELECT FU.NOME, FU.CPF, COUNT(S.FESTA), SUM(FE.DURACAO)
	FROM SUPERVISOR JOIN FUNCIONARIO FU
	ON SUPERVISOR.CPF=FU.CPF
	JOIN SUPERVISIONA S
	ON FU.CPF=S.SUPERVISOR
	JOIN FESTA F
	ON F.CODIGO=S.FESTA
	WHERE 